---
platform: linux

image_resource:
  type: docker-image
  source: {repository: boshcpi/aws-cpi-release}

inputs:
  - name: bosh-cpi-src
  - name: environment
  - name: stemcell
  - name: director-state
  - name: builder-src
  - name: bosh-cli

run:
  path: builder-src/ci/tasks/run-upload-test.sh

params:
  BOSH_DEBUG_LEVEL:     info
