---
groups:
- name: all-alicloud
  jobs:
  - ubuntu-xenial-stemcell-250

- name: "ubuntu-xenial"
  jobs:
  - ubuntu-xenial-stemcell-250

shared:
- &put-stemcells-index
  put: stemcells-index
  params:
    repository: stemcells-index-output
    rebase: true
- &get-stemcell
  get: input-stemcell
  version: every
  trigger: true
  params:
    preserve_filename: true
- &get-builder-src
  get: builder-src
  resource: builder-src
- &get-aliyun-cli
  get: aliyun-cli
  resource: aliyun-cli

- &build-stemcell-task
  task: build-stemcell
  file: builder-src/ci/tasks/build.yml
  input_mapping:
    input-stemcell: input-stemcell
    builder-src: builder-src
    aliyun-cli: aliyun-cli
  output_mapping:
    light-stemcell: light-stemcell
  params:
    bosh_io_bucket_name: "bosh-alicloud-light-stemcells"
    ami_description: ((publish__description))
    ami_region: ((publish__region))
    ami_access_key: ((publish__access_key))
    ami_secret_key: ((publish__secret_key))
    ami_bucket_name: ((publish__bucket))
    ami_destinations: eu-central-1 cn-beijing cn-hangzhou

- &publish-stemcell-and-checksum
  task: publish-stemcell-and-checksum
  file: builder-src/ci/tasks/publish-stemcell-and-checksum.yml
  input_mapping:
    builder-src: builder-src
    light-stemcell: light-stemcell
  params:
    AWS_ACCESS_KEY_ID: ((alicloud_light_stemcells_access_key_id))
    AWS_SECRET_ACCESS_KEY: ((alicloud_light_stemcells_secret_access_key))
    AWS_DEFAULT_REGION: ((alicloud_light_stemcells_region))
    OUTPUT_BUCKET: ((alicloud_light_stemcells_bucket_name))

jobs:
- name: ubuntu-xenial-stemcell-250
  serial: true
  plan:
  - <<: *get-stemcell
    resource: ubuntu-xenial-stemcell-250
  - <<: *get-builder-src
  - <<: *get-aliyun-cli
  - <<: *build-stemcell-task
  - put: bosh-full-stemcell
    params: {file: light-stemcell/*.tgz}
  - get: stemcells-index
  - <<: *publish-stemcell-and-checksum
  - <<: *put-stemcells-index

resources:
- name: stemcells-index
  type: git
  source:
#    uri: git@github.com:bosh-io/stemcells-cpi-index.git
    uri: git@github.com:xiaozhu36/stemcells-cpi-index.git
    branch: master
    private_key: ((stemcells_index__github_key))

- name: builder-src
  type: git
  source:
    uri: https://github.com/aliyun/bosh-alicloud-light-stemcell-builder
    branch: dev

- name: ubuntu-xenial-stemcell-250
  type: bosh-io-stemcell
  source:
    name: bosh-alicloud-kvm-ubuntu-xenial-go_agent
    force_regular: true
    version_family: "250"

- name: bosh-full-stemcell
  type: s3
  source:
    regexp: light-bosh-(.*).tgz
    bucket: ((certification__bucket))
    region_name: eu-central-1
    endpoint: oss-eu-central-1.aliyuncs.com
    access_key_id: ((certification__bucket_access_key))
    secret_access_key: ((certification__bucket_secret_key))

- name: aliyun-cli
  type: github-release
  source:
    owner: aliyun
    repository: aliyun-cli

resource_types:
- name: metalink-repository
  type: docker-image
  source:
    repository: dpb587/metalink-repository-resource
- name: terraform_type
  type: docker-image
  source:
    repository: ljfranklin/terraform-resource
